name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create built-site directory
        run: mkdir ${GITHUB_WORKSPACE}/built-site

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cd /home/runner/work/stephenlamonline.github.io/stephenlamonline.github.io
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'stephenlam'
          git config user.email 'stephenlamonline@gmail.com'
          git commit -m 'Updated site'
          git push
